# AI assistance: parts of this file were written with Claude (Anthropic) and thoroughly reviewed.
"""Node-free tests for the server side of the page's Viem layer (/api/contracts, /api/identity-hash,
/api/record-commitment, /api/state and the Content-Security-Policy).
"""
import json
import re
import unittest
from pathlib import Path

from app import chain, records
from app.models import Reason, ChainUnavailable, DeploymentUnavailable, ArtifactUnavailable
from tests.test_ui import UITestCase, NODE_DOWN, NO_DEPLOYMENT, NO_ARTIFACTS
from ui import actions, server

# a stand-in ABI per contract: FakeNode's contracts have none, and the real artifacts are git ignored
ABIS = {
    name: [
        {"type": "function", "name": "view", "inputs": [], "outputs": [], "stateMutability": "view"},
        {"type": "error", "name": f"{name}Error", "inputs": []},
    ]
    for name in chain.CONTRACT_NAMES
}
POLICY = ("default-src 'self'; connect-src 'self' http://127.0.0.1:8545; frame-ancestors 'none'; base-uri 'none'; "
          "form-action 'self'")
BUNDLE_HEADER = "// generated by npm run build:ui, do not edit"
ENTRY = server.STATIC_DIR / "src" / "viem.js"
CHAIN_JS = server.STATIC_DIR / "chain.js"
VIEWS = ("get_user_info", "get_consent", "get_reward_balance", "list_access_events")


class ViemTestCase(UITestCase):
    def setUp(self):
        super().setUp()
        for name, contract in self.fake.contracts.items():
            contract.abi = ABIS[name]

    def identity_hash(self, role, status=200):
        return self.call("GET", f"/api/identity-hash?role={role}", status=status)

    def called(self):
        return {name for name, _ in self.fake.calls}


class ContractsTests(ViemTestCase):
    def test_addresses_and_abis_only_after_the_checks(self):
        self.ready()
        answer = self.call("GET", "/api/contracts")
        self.assertEqual(answer["status"], "ok")
        details = answer["details"]
        self.assertEqual(details["contracts"], {
            name: {"address": self.fake.contracts[name].address, "abi": ABIS[name]} for name in chain.CONTRACT_NAMES
        })
        self.assertEqual(details["accounts"], self.fake.addresses)
        self.assertEqual((details["chain_id"], details["rpc_url"]), (31337, "http://127.0.0.1:8545"))
        self.assertEqual(details["scopes"], {"MEASLES_STATUS": 1, "VACCINATION_SCHEDULE": 2})
        self.assertEqual(details["reasons"], {reason.name: int(reason) for reason in Reason})
        # every contract went through load_contract's checks; nothing was sent or read from the contracts
        self.assertEqual([call["name"] for call in self.fake.calls_to("load_contract")], list(chain.CONTRACT_NAMES))
        self.assertEqual(self.called(), {"connect", "select_account", "load_contract"})

    def test_a_missing_or_stale_deployment_serves_nothing(self):
        for failure in (DeploymentUnavailable("deployment unavailable"),
                        DeploymentUnavailable("deployment is from another run of the node"),
                        DeploymentUnavailable("contract code does not match the deployment")):
            self.fake.failures["load_contract"] = failure
            answer = self.call("GET", "/api/contracts")
            self.assertEqual((answer["status"], answer["message"]), ("unavailable", NO_DEPLOYMENT))
            self.assertEqual(answer["details"], {})

    def test_node_down_and_missing_artifacts_keep_their_messages(self):
        self.fake.failures["connect"] = ChainUnavailable("RPC connection failed")
        self.assertEqual(self.call("GET", "/api/contracts")["message"], NODE_DOWN)
        # the message names a path, which must not reach the page
        self.fake.failures["load_contract"] = ArtifactUnavailable("/Users/somebody/artifacts")
        answer = self.call("GET", "/api/contracts")
        self.assertEqual((answer["message"], answer["details"]), (NO_ARTIFACTS, {}))

    def test_a_node_that_stops_midway_serves_nothing(self):
        self.fake.failures["select_account"] = ChainUnavailable("RPC request failed")
        answer = self.call("GET", "/api/contracts")
        self.assertEqual((answer["message"], answer["details"]), (NODE_DOWN, {}))

    def test_another_host_is_refused_before_any_chain_call(self):
        status, _, body = self.request("GET", "/api/contracts", headers={"Host": f"evil.example:{self.port}"})
        self.assertEqual(status, 403)
        self.assertNotIn(b"abi", body)
        self.assertEqual(self.fake.calls, [])


class IdentityHashTests(ViemTestCase):
    def test_each_registering_role_gets_its_salted_hash_only(self):
        self.ready()
        for label in records.REGISTERING_LABELS:
            answer = self.identity_hash(label)
            expected = records.prepare_identity(*records.identity_paths(self.settings, label))
            self.assertEqual(answer["status"], "ok")
            self.assertEqual(answer["details"], {"identity_hash": f"0x{expected.hex()}"})
        # hashing needs no node
        self.assertEqual(self.fake.calls, [])

    def test_other_roles_are_refused(self):
        self.ready()
        for role in ("deployer", "clinic"):
            answer = self.identity_hash(role, status=400)
            self.assertEqual((answer["status"], answer["message"]), ("invalid", "only guardian, school and doctor register"))
        for path in ("/api/identity-hash?role=teacher", "/api/identity-hash?role=", "/api/identity-hash"):
            answer = self.call("GET", path, status=400)
            self.assertEqual((answer["status"], answer["message"]), ("invalid", "unknown role"))

    def test_missing_files_are_unavailable_without_a_path(self):
        self.assertEqual(self.identity_hash("guardian")["message"], "unavailable: identity unavailable")
        self.ready()
        Path(records.identity_paths(self.settings, "school")[1]).unlink()
        self.assertEqual(self.identity_hash("school")["message"], "unavailable: salt unavailable")


class RecordCommitmentTests(ViemTestCase):
    def test_the_commitment_and_nothing_else(self):
        commitment = self.ready()
        status, _, raw = self.request("GET", "/api/record-commitment")
        self.assertEqual(status, 200)
        answer = json.loads(raw)
        self.answers.append(raw.decode())
        self.assertEqual(answer["details"], {"commitment": f"0x{commitment.hex()}"})
        for text in (b"salt", b"child_id", b"vaccinations", b"covers", b"MMR"):
            self.assertNotIn(text, raw)
        self.assertEqual(self.fake.calls, [])

    def test_a_missing_record_or_salt_is_unavailable(self):
        self.assertEqual(self.call("GET", "/api/record-commitment")["message"], "unavailable: local record unavailable")
        self.ready()
        Path(self.settings["vaccination_salt_file"]).unlink()
        self.assertEqual(self.call("GET", "/api/record-commitment")["message"], "unavailable: salt unavailable")


class LeanStateTests(ViemTestCase):
    def test_chain_views_0_leaves_the_contract_views_to_the_page(self):
        self.ready()
        state = self.call("GET", "/api/state?chain_views=0")
        self.assertTrue(state["deployment"]["deployed"])
        self.assertTrue(state["local"]["ready"])
        self.assertEqual(state["accounts"], self.fake.addresses)
        self.assertEqual(
            (state["registrations"], state["record"], state["consents"], state["rewards"], state["audit"]),
            ({}, None, [], {}, []),
        )
        self.assertFalse(self.called() & set(VIEWS))
        # the default is the full snapshot, as before
        self.assertTrue(self.get_state()["registrations"]["guardian"]["registered"])
        self.assertTrue(self.called() >= set(VIEWS))


class PolicyTests(ViemTestCase):
    def test_every_response_allows_connections_to_the_node_only(self):
        for method, path, headers in (
            ("GET", "/", {}), ("GET", "/api/state", {}), ("GET", "/static/vendor/viem.js", {}), ("GET", "/api/contracts", {}),
            ("GET", "/api/identity-hash?role=deployer", {}), ("GET", "/nothing", {}), ("PUT", "/api/setup", {}),
            ("GET", "/api/state", {"Host": "evil.example"}), ("POST", "/api/setup", {"Origin": "http://evil.example"}),
        ):
            _, sent, _ = self.request(method, path, {} if method == "POST" else None, headers)
            self.assertEqual(sent["content-security-policy"], POLICY, (method, path))
            for name, value in server.SECURITY_HEADERS:
                self.assertEqual(sent[name.lower()], value, (method, path, name))

    def test_only_a_plain_http_url_names_its_origin(self):
        for url, origin in (
            ("http://127.0.0.1:8545", "http://127.0.0.1:8545"), ("http://localhost:8545/", "http://localhost:8545"),
            ("HTTP://LOCALHOST:8545", "http://localhost:8545"), ("https://node.example:443/rpc", "https://node.example:443"),
            ("http://127.0.0.1", "http://127.0.0.1"),
        ):
            self.assertEqual(server.rpc_origin(url), origin, url)
        for url in (
            None, 42, "", "ws://127.0.0.1:8545", "http://user:pw@127.0.0.1:8545", "http://user@127.0.0.1:8545",
            "http://[::1]:8545", "http://例.jp:8545", "http://x;script-src *:8545", "http://127.0.0.1:8545;script-src *",
            "http://127.0.0.1:8545\r\nX-Evil: 1", "http://'x':8545", "http://a b:8545", "http://127.0.0.1:99999",
            "http:///rpc",
        ):
            self.assertIsNone(server.rpc_origin(url), url)
        self.assertEqual(
            server.content_security_policy(None),
            "default-src 'self'; connect-src 'self'; frame-ancestors 'none'; base-uri 'none'; form-action 'self'",
        )

    def test_a_bad_or_missing_rpc_url_leaves_the_page_no_way_to_the_node(self):
        for settings in (dict(self.settings, rpc_url="http://user:pw@127.0.0.1:8545"), {
            key: value for key, value in self.settings.items() if key != "rpc_url"
        }):
            other = server.UIServer(settings, self.settings_file, port=0)
            self.addCleanup(other.server_close)
            self.assertEqual((other.rpc_origin, other.rpc_url), (None, ""))
            self.assertNotIn("8545", other.csp)
        # the page gets the URL rebuilt from its checked parts, never the setting as written
        other = server.UIServer(dict(self.settings, rpc_url=" http://127.0.0.1:8545/rpc"), self.settings_file, port=0)
        self.addCleanup(other.server_close)
        self.assertEqual(other.rpc_url, "http://127.0.0.1:8545/rpc")


class PageFileTests(ViemTestCase):
    def test_the_prebuilt_bundle_is_served_with_its_header(self):
        status, headers, body = self.request("GET", "/static/vendor/viem.js")
        self.assertEqual(status, 200)
        self.assertEqual(headers["content-type"], "text/javascript; charset=utf-8")
        self.assertEqual(body.decode().splitlines()[0], BUNDLE_HEADER)
        self.assertIn(b"var Viem=", body)
        # the entry and the folders are not pages
        for path in ("/static/src/viem.js", "/static/vendor/", "/static/vendor/viem.js.map", "/static/src/"):
            self.assertEqual(self.request("GET", path)[0], 404, path)

    def test_the_page_loads_viem_first(self):
        page = (server.STATIC_DIR / "index.html").read_text()
        scripts = re.findall(r'<script src="/static/([^"]+)" defer></script>', page)
        self.assertEqual(scripts, ["vendor/viem.js", "chain.js", "app.js", "demo.js"])

    def test_everything_chain_js_takes_from_viem_is_in_the_bundle(self):
        used = set(re.findall(r"\bViem\.(\w+)", CHAIN_JS.read_text()))
        entry = ENTRY.read_text()
        exported = {name.strip() for block in re.findall(r"export \{([^}]*)\}", entry) for name in block.split(",")} - {""}
        bundle = (server.STATIC_DIR / "vendor" / "viem.js").read_text()
        self.assertTrue(used)
        self.assertLessEqual(used, exported)
        for name in exported:
            self.assertRegex(bundle, rf"\b{name}:\(\)=>", name)
        self.assertIn("viem (https://viem.sh) - MIT License", bundle)

    def test_chain_js_shows_the_console_texts(self):
        text = CHAIN_JS.read_text()
        self.assertIn(f"'{actions.NODE_UNAVAILABLE_MESSAGE}'", text)
        for part in ("`rejected: ${", "'pending: not confirmed'", "`failed: ${", "'rejected: Reverted'"):
            self.assertIn(part, text)
        # the page asks for the lean snapshot and reads the contract views itself
        self.assertIn("/api/state?chain_views=0", (server.STATIC_DIR / "app.js").read_text())


if __name__ == "__main__":
    unittest.main()
